language: c

# Supply at least one RACKET_VERSION environment variable definition
# here. RACKET_VERSION is used by the install-racket.sh script
# (specifed below under before_install) to select the version of
# Racket to download and install.
#
# If you supply more than one, you can create multiple builds (a
# Travis-CI build matrix resulting in multiple builds). You can use
# this to test against multiple Racket versions.
env:
 - RACKET_VERSION=5.3.4
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.92
 - RACKET_VERSION=6.0
 - RACKET_VERSION=HEAD

before_install:
# Temporarily use raw.github.com to test this. After tests OK, will
# make a v0.5 and change this back to be an example of the right way
# to do this.
- curl https://raw.github.com/greghendershott/travis-racket/master/install-racket.sh | bash
# - curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.4/install-racket.sh | bash

install:

before_script:

# Here supply steps such as raco make, raco test, etc.  Note that you
# need to supply /usr/racket/bin/ -- it's not in PATH. You can run
# `raco pkg install --deps search-auto <pkg>` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .

# NOTE: If your repo is a Racket package with an info.rkt that
# includes some `deps`, the following is more elegant:
#
# script:
# - cd ..   # Travis did a cd into the dir. Back up, for the next:
# - /usr/racket/bin/raco pkg install --deps search-auto --link <pkg>
# - /usr/racket/bin/raco test -x -p <pkg>

after_script:
